name: Script time

on:
  push:
    branches:
      - main

jobs:
  time-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run time command on Python scripts
      run: |
        find . -name "*.py" -type f -exec time -f "%E" python {} \;
